### ISSUE TITLE
 travis CI project's name change

### ISSUE THREAD

**Issue by chairco** [Python-Logging-For-Human/lazy_logger#10]
new url:
[https://travis-ci.org/Python-Logging-For-Human/lazy_logger](https://travis-ci.org/Python-Logging-For-Human/lazy_logger)

need update README.md

**Comment by timtan** [comment]
臨時換名字真是可怕

**Comment by timtan** [comment]
@jackklpan 有空調整一下嗎？

**Comment by chairco** [comment]
solve `e6d7c90`

**Comment by timtan** [comment]
喔喔喔

超快

**Comment by chairco** [comment]
哈，謝謝大家好快都上來看了
