### ISSUE TITLE
README

### ISSUE THREAD

**Issue by WendellLiu** [Python-Logging-For-Human/lazy_logger#11]
因為我不知道能去哪先和大家討論，就先push了，真抱歉

我修改了README.md
主要是修正一些typo和加入`logger.patch`的用法

@chairco 可以看看有沒有什麼是我誤會你的意思，或是我也寫錯的大家再直接修改

**Comment by timtan** [comment]
讚！

**Comment by chairco** [comment]
@WendellLiu Don't worry, 反正改了有意見自然會在 issue 裡面說。

剛剛讀了一遍目前這樣改比原先直接翻譯好很多(先承認原本文法怪怪)，但不確定要不要加入更多參數說明，或是 README.md 就用現在 quick start 方式(符合 lazy 的使用者)簡單讓大家快速上手。

先改謝，看看 @timtan 哥有沒有其他建議? 還是讓這 issue 繼續掛著，留一兩天在做些完善?

**Comment by timtan** [comment]
我是覺得現在很　ok 了。　　看大家有沒有什麼實際應用　logger 的　case 需要整合進來。

**Comment by chairco** [comment]
那先關閉了。
